### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Moflows** [Instinctlol/automatic-twitch-recorder#36]
After the streamer finishes streaming this error executes. And he is stuck at "Live". Not sure if it can continue to wait and then start streaming again if the streamer decides to do so.

(Cmd) add officialandypyro best
Successfully added officialandypyro to watchlist.
(Cmd) time 10
Interval is now set to 10 seconds.
(Cmd) download_folder I:\Twitch-Recording-1
Download folder is now set to 'I:\Twitch-Recording-1' .
(Cmd) start
Daemon is started.
(Cmd) OfficialAndyPyro is live. Saving stream in best quality to I:\Twitch-Recording-1\2020-12-29 23.19.05 - OfficialAndyPyro - Good morning Tarkov.ts.
Finished watching officialandypyro
error:concurrent.futures:exception calling callback for <Future at 0x5fcb880 state=finished returned NoneType>
Traceback (most recent call last):
  File "C:\Users\Moflows\AppData\Local\Programs\Python\Python38-32\lib\concurrent\futures\_base.py", line 328, in _invoke_callbacks
    callback(self)
  File "C:\Users\Moflows\Desktop\Twitch-Record-2\daemon.py", line 136, in _watcher_callback
    streamer = streamer_dict['user_info']['login']
TypeError: 'NoneType' object is not subscriptable

Daemon is already running.
(Cmd) list
Live: 'officialandypyro'
Offline:
(Cmd) exit
Daemon exited successfully
PS C:\Users\Moflows\Desktop\Twitch-Record-2> python main.py
(Cmd) start
Daemon is started.
(Cmd) add officialandypyro best
Successfully added officialandypyro to watchlist.
(Cmd) list
Live:
Offline: 'officialandypyro'

-----

pip install -r requirements.txt
Requirement already satisfied: attrs==20.3.0 in c:\users\moflows\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 1)) (20.3.0)
Requirement already satisfied: certifi==2020.12.5 in c:\users\moflows\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 2)) (2020.12.5)
Requirement already satisfied: chardet==4.0.0 in c:\users\moflows\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 3)) (4.0.0)
Requirement already satisfied: idna==2.10 in c:\users\moflows\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 4)) (2.10)
Requirement already satisfied: importlib-metadata==3.3.0 in c:\users\moflows\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 5)) (3.3.0)
Requirement already satisfied: iso-639==0.4.5 in c:\users\moflows\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 6)) (0.4.5)
Requirement already satisfied: iso3166==1.0.1 in c:\users\moflows\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 7)) (1.0.1)
Requirement already satisfied: isodate==0.6.0 in c:\users\moflows\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 8)) (0.6.0)
Requirement already satisfied: jsonschema==3.2.0 in c:\users\moflows\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 9)) (3.2.0)
Requirement already satisfied: pathvalidate==2.3.1 in c:\users\moflows\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 10)) (2.3.1)
Requirement already satisfied: pycryptodome==3.9.9 in c:\users\moflows\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 11)) (3.9.9)
Requirement already satisfied: pyrsistent==0.17.3 in c:\users\moflows\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 12)) (0.17.3)
Requirement already satisfied: PySocks==1.7.1 in c:\users\moflows\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 13)) (1.7.1)
Requirement already satisfied: requests==2.25.1 in c:\users\moflows\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 14)) (2.25.1)
Requirement already satisfied: six==1.15.0 in c:\users\moflows\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 15)) (1.15.0)
Requirement already satisfied: streamlink==2.0.0 in c:\users\moflows\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 16)) (2.0.0)
Requirement already satisfied: typing-extensions==3.7.4.3 in c:\users\moflows\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 17)) (3.7.4.3)
Requirement already satisfied: urllib3==1.26.2 in c:\users\moflows\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 18)) (1.26.2)
Requirement already satisfied: websocket-client==0.57.0 in c:\users\moflows\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 19)) (0.57.0)
Requirement already satisfied: zipp==3.4.0 in c:\users\moflows\appdata\local\programs\python\python38-32\lib\site-packages (from -r requirements.txt (line 20)) (3.4.0)
Requirement already satisfied: setuptools in c:\users\moflows\appdata\local\programs\python\python38-32\lib\site-packages (from jsonschema==3.2.0->-r requirements.txt (line 9)) (50.3.2)

**Comment by CipherdevNL** [comment]
Hi Moflows,

Thank you for the bug report, in the linked issue (#26) we're working on a solution for this issue.
I expect to make the fix available in about 1-2 weeks :).

**Comment by b7leung** [comment]
This issue seems to now happen every time for me, making the program unusable. I wonder if there are any updates on a fix/workaround for this?
