### ISSUE TITLE
Exception finished returned NoneType

### ISSUE THREAD

**Issue by PhreakyFreay** [Instinctlol/automatic-twitch-recorder#39]
Everytime a Streamer ends the stream I get an error:
```
 error:concurrent.futures:exception calling callback for <Future at 0x7f506088931
0 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 329, in _invoke_ca
llbacks
    callback(self)
  File "/home/user/atw/automatic-twitch-recorder/daemon.py", line 136, in _watche
r_callback
    streamer = streamer_dict['user_info']['login']
TypeError: 'NoneType' object is not subscriptable
```
I use python 3.2.9
Streamlink 2.0.0

After this error the streamer stays "online" in the list.

**Comment by ramflores91** [comment]
I get the same error. What was the fix for this issue?
